# Project: coffee
# Makefile created by Dev-C++ 4.9.9.2
# and modified by fralaz1971

CC   = gcc
OBJ  = coffee.o
LINKOBJ  = coffee.o
LIBS =  -L.  -g3
INCS =  -I.
CXXINCS =  -I.  -Iinclude
BIN  = coffee
CXXFLAGS = $(CXXINCS)   -g
CFLAGS = $(INCS)   -g
RM = rm -f

.PHONY: all clean clean-custom

all: coffee

clean: clean-custom
	${RM} $(OBJ) $(BIN)

$(BIN): $(OBJ)
	$(CC) $(LINKOBJ) -o coffee $(LIBS)

coffee.o: coffee.c
	$(CC) -c coffee.c -o coffee.o $(CFLAGS)
